name: Build and Create DLL

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Verify repository structure
      run: dir
      shell: pwsh

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Configure with CMake
      run: cmake -S . -B build
      shell: pwsh

    - name: Build project
      run: cmake --build build --config Release
      shell: pwsh

    - name: Create DLL
      run: |
        mkdir -p output
        cp build\Release\*.dll output\
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: zxing-dll
        path: output\*.dll
