name: Build and Create DLL

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: zxing-cpp/zxing-cpp

    - name: Verify repository structure
      run: |
        echo "Current directory:"
        pwd
        echo "Listing files in the current directory:"
        dir
      shell: pwsh

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Set up dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install ninja
      shell: pwsh

    - name: Configure with CMake
      run: cmake -S . -B build -G Ninja
      shell: pwsh

    - name: Build project
      run: cmake --build build --config Release
      shell: pwsh

    - name: Create DLL
      run: |
        mkdir -p output
        cp build\Release\*.dll output\
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: zxing-dll
        path: output\*.dll
